<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.scheduling.config.AnnotationDrivenBeanDefinitionParserTests" tests="5" skipped="0" failures="0" errors="0" timestamp="2020-12-16T17:33:54" hostname="DESKTOP-EMRC5FU" time="0.034">
  <properties/>
  <testcase name="asyncPostProcessorExceptionHandlerReference" classname="org.springframework.scheduling.config.AnnotationDrivenBeanDefinitionParserTests" time="0.009"/>
  <testcase name="scheduledPostProcessorSchedulerReference" classname="org.springframework.scheduling.config.AnnotationDrivenBeanDefinitionParserTests" time="0.007"/>
  <testcase name="asyncPostProcessorRegistered" classname="org.springframework.scheduling.config.AnnotationDrivenBeanDefinitionParserTests" time="0.006"/>
  <testcase name="asyncPostProcessorExecutorReference" classname="org.springframework.scheduling.config.AnnotationDrivenBeanDefinitionParserTests" time="0.005"/>
  <testcase name="scheduledPostProcessorRegistered" classname="org.springframework.scheduling.config.AnnotationDrivenBeanDefinitionParserTests" time="0.007"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[Dez 17, 2020 1:33:54 AM ClientIntermediary close
INFORMATION: java.io.IOException: The connection is not currently established.
java.io.IOException: The connection is not currently established.
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.checkState(ClientSynchroMessageConnectionImpl.java:617)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl.sendOneWay(ClientSynchroMessageConnectionImpl.java:202)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:300)
	at javax.management.remote.generic.GenericConnector.close(GenericConnector.java:271)
	at javax.management.remote.generic.ClientIntermediary$GenericClientCommunicatorAdmin.doStop(ClientIntermediary.java:897)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.restart(ClientCommunicatorAdmin.java:172)
	at com.sun.jmx.remote.opt.internal.ClientCommunicatorAdmin.gotIOException(ClientCommunicatorAdmin.java:73)
	at javax.management.remote.generic.GenericConnector$RequestHandler.execute(GenericConnector.java:662)
	at com.sun.jmx.remote.generic.ClientSynchroMessageConnectionImpl$RemoteJob.run(ClientSynchroMessageConnectionImpl.java:568)
	at com.sun.jmx.remote.opt.util.ThreadService$ThreadServiceJob.run(ThreadService.java:248)
	at com.sun.jmx.remote.opt.util.JobExecutor.run(JobExecutor.java:99)

]]></system-err>
</testsuite>
