<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" tests="11" skipped="0" failures="0" errors="0" timestamp="2020-12-16T17:33:53" hostname="DESKTOP-EMRC5FU" time="0.072">
  <properties/>
  <testcase name="configuredThroughNamespace" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.05"/>
  <testcase name="taskExecutorByBeanName" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.002"/>
  <testcase name="taskExecutorByBeanType" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.002"/>
  <testcase name="exceptionHandlerThrowsUnexpectedException" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.002"/>
  <testcase name="handleExceptionWithCustomExceptionHandler" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.0"/>
  <testcase name="threadNamePrefix" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.001"/>
  <testcase name="handleExceptionWithFuture" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.008"/>
  <testcase name="proxyCreated" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.0"/>
  <testcase name="handleExceptionWithListenableFuture" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.005"/>
  <testcase name="invokedAsynchronously" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.0"/>
  <testcase name="invokedAsynchronouslyOnProxyTarget" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[Dez 17, 2020 1:33:53 AM ClientCommunicatorAdmin restart
WARNUNG: Failed to restart: java.net.ConnectException: Connection refused: connect
]]></system-err>
</testsuite>
